name: Run CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean test -Dtest=!WindowsStorageDeviceDetectorTest

  run-ci-tests-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        java: [ '8' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with coverage
        run: mvn clean test -Dtest=WindowsStorageDeviceDetectorTest